[package]
name = "devzen-matrix-rss-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix-sdk = { version = "0.10", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "socks"] }
rss = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
mime = "0.3.17"
